### ISSUE TITLE
Kinda the same as ResumableFunctions?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaFolds/GeneratorsX.jl#1]
See https://github.com/BenLauwens/ResumableFunctions.jl

Feels like the same. Any compare and contrast between the two?

**Comment by tkf** [comment]
Yes, that's a very good question!  It's actually the second time I get the same question: https://discourse.julialang.org/t/rfc-ann-floops-jl-fast-generic-for-loops-foldl-for-humans/37876/42.  My answer was:

> The implementation of ResumableFunctions.jl is based on mutation so it’s not the best choice for performance (especially for type-changing state) and parallelism.

I think I should add this in the README.
