### ISSUE TITLE
Is it possible to defined a `length` on the generator?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaFolds/GeneratorsX.jl#2]
I tried

```julia
 @generator function meh()
       for i in 1:10
           @yield i
       end
end;

using Base.Threads

@threads for i in meh()
       print(i)
end
```

but it complains about the length. Is possible to set a `length`. E.g. 

```julia 
 @generator length = 10 function meh()
       for i in 1:10
           @yield i
       end
end;
```

**Comment by tkf** [comment]
I think a more extensible way is to let people use `@generator` macro on existing types. This way, you can implement arbitrary methods on it. See `Count` example in README I just added.
